import Head from "next/head";
import React from "react";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shreya Vaidya | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/../public/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
