import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shreya Vaidya | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/../public/favicon.ico" />
        
      </Head>

      <Navbar />
    </div>
  );
}
